### ISSUE TITLE
error[E0599]: no variant or associated item named `Json` found

### ISSUE THREAD

**Issue by makorne** [bool-rus/ydb-unofficial#4]
//use ydb::Value;    It works with ydb official

use ydb_unofficial::generated::ydb::value::Value;  

```
let json = Value::Json("{\"id\":\"\",\"name\":\"\"}".to_string());
                            ^^^^ variant or associated item not found in `Value`
error[E0599]: no variant or associated item named `Json` found for enum `ydb_unofficial::generated::ydb::value::Value` in the current scope
```
How to store json?
Thanks!

**Comment by bool-rus** [comment]
hi) json type not yet implemented.

**Comment by bool-rus** [comment]
hah, it's already impelmentd in simple ydb (without sqlx) 
@makorne You need to use TypedValue{type: Json, value: TextValue}

**Comment by makorne** [comment]
But I cant use this

```
use ydb_unofficial::generated::ydb::r#type::PrimitiveTypeId::Json;
use ydb_unofficial::generated::ydb::TypedValue;

```
like 
```
TypedValue{ r#type: Json, value: Some(json_str.to_owned())}

                     mismatched types [E0308] expected `Option<Type>`, found `PrimitiveTypeId`
```
becouse ydb_unofficial::generated::ydb::Type   dont have a  Json type:

```
Enum [ydb_grpc_bindings](https://docs.rs/ydb-grpc-bindings/0.0.1/ydb_grpc_bindings/index.html)::[generated](https://docs.rs/ydb-grpc-bindings/0.0.1/ydb_grpc_bindings/generated/index.html)::[ydb](https://docs.rs/ydb-grpc-bindings/0.0.1/ydb_grpc_bindings/generated/ydb/index.html)::[type](https://docs.rs/ydb-grpc-bindings/0.0.1/ydb_grpc_bindings/generated/ydb/type/index.html)::[Type](https://docs.rs/ydb-grpc-bindings/0.0.1/ydb_grpc_bindings/generated/ydb/type/enum.Type.html#)
[source](https://docs.rs/ydb-grpc-bindings/0.0.1/src/ydb_grpc_bindings/generated/ydb.rs.html#418-450) ·
```

pub enum Type {
    TypeId([i32](https://doc.rust-lang.org/nightly/std/primitive.i32.html)),
    DecimalType([DecimalType](https://docs.rs/ydb-grpc-bindings/0.0.1/ydb_grpc_bindings/generated/ydb/struct.DecimalType.html)),
    OptionalType([Box](https://doc.rust-lang.org/nightly/alloc/boxed/struct.Box.html)<[OptionalType](https://docs.rs/ydb-grpc-bindings/0.0.1/ydb_grpc_bindings/generated/ydb/struct.OptionalType.html)>),
    ListType([Box](https://doc.rust-lang.org/nightly/alloc/boxed/struct.Box.html)<[ListType](https://docs.rs/ydb-grpc-bindings/0.0.1/ydb_grpc_bindings/generated/ydb/struct.ListType.html)>),
    TupleType([TupleType](https://docs.rs/ydb-grpc-bindings/0.0.1/ydb_grpc_bindings/generated/ydb/struct.TupleType.html)),
    StructType([StructType](https://docs.rs/ydb-grpc-bindings/0.0.1/ydb_grpc_bindings/generated/ydb/struct.StructType.html)),
    DictType([Box](https://doc.rust-lang.org/nightly/alloc/boxed/struct.Box.html)<[DictType](https://docs.rs/ydb-grpc-bindings/0.0.1/ydb_grpc_bindings/generated/ydb/struct.DictType.html)>),
    VariantType([VariantType](https://docs.rs/ydb-grpc-bindings/0.0.1/ydb_grpc_bindings/generated/ydb/struct.VariantType.html)),
    TaggedType([Box](https://doc.rust-lang.org/nightly/alloc/boxed/struct.Box.html)<[TaggedType](https://docs.rs/ydb-grpc-bindings/0.0.1/ydb_grpc_bindings/generated/ydb/struct.TaggedType.html)>),
    VoidType([i32](https://doc.rust-lang.org/nightly/std/primitive.i32.html)),
    NullType([i32](https://doc.rust-lang.org/nightly/std/primitive.i32.html)),
    EmptyListType([i32](https://doc.rust-lang.org/nightly/std/primitive.i32.html)),
    EmptyDictType([i32](https://doc.rust-lang.org/nightly/std/primitive.i32.html)),
    PgType([PgType](https://docs.rs/ydb-grpc-bindings/0.0.1/ydb_grpc_bindings/generated/ydb/struct.PgType.html)),
}

Please any example?
